import numpy as np

ITERATIONS = 5

DOA = 60
DELAYS = [160.4]
PREAMBLE_LENGTH = 127
PREAMBLE_ROOT = 1
SNR = [-8, -6, -4, -2, 0, 2, 4, 6, 8, 10]
FILTER_SPAN = 10
SPS = 8
BIT_AMOUNT = 60000

SPEED_OF_LIGHT = 3e8
BASE_BAND = 4e6
SYMBOL_FREQUENCY = BASE_BAND * 2

FREQ_OFFSET = 0

CARRIER_FREQ = 2.4e9
ANTENNAS_DISTANCE = [5e-2, 5e-2, 5e-2]
ANTENNA2_PHASE_SHIFT_VALUES = []
for i in range(len(ANTENNAS_DISTANCE)):
    ANTENNA2_PHASE_SHIFT_VALUES.append(2*np.pi*CARRIER_FREQ*ANTENNAS_DISTANCE[i] * np.sin(np.radians(DOA))/ SPEED_OF_LIGHT)

DOA_methods_amount = 3
wavelength = SPEED_OF_LIGHT / CARRIER_FREQ
